language: node_js
node_js:
  - "8"
sudo: required

services:
  - docker

before_install:
  - docker build -t shyam/docker-react -f Dockerfile.dev .

script:
  - docker run -it -v /app/frontend/node_modules -v $(pwd):/app/frontend shyam/docker-react npm run test -- --coverage

