sudo: required
services:
  - docker


before_install:
  - docker build -t shyam/docker-react -f Dockerfile.dev .

script:
  - docker run shyam/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker"
  env: "Docker-env"
  bucker_name: "elasticbeanstalk-ap-south-1-195597906524"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key:
    secure: "$AWS_SECRET_KEY"
