language: node_js
node_js:
  - "8"
sudo: required

services:
  - docker

before_install:
  - docker build -t shyam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shyam/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-195597906524"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  edge: true

after_deploy:
  - echo "done deploying"
