sudo: required

install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'

services:
  - docker


before_install:
  - docker build -t shyam/docker-react -f Dockerfile.dev .

script:
  - docker run shyam/docker-react npm run test -- --coverage
