FROM node:alpine

RUN apk update -qq && apk install -y build-essential libpq-dev nodejs && apk install npm

WORKDIR /app/frontend

COPY ./app/Gemfile /webapp/Gemfile
COPY ./app/Gemfile.lock /webapp/Gemfile.lock

COPY ./package.json ./

RUN npm install

COPY ./ ./


CMD npm run start
