version: "3"
services:
  node-app:
    restart: on-failure
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/frontend/node_modules
      - .:/app/frontend
